_target_: stapler.models.stapler_transformer.STAPLERTransformer
output_classification: False
num_tokens: 25 # num_tokens
emb_dim: 25 # emb_dim
cls_dropout: 0.4 # not used in pre-train
emb_dropout: 0.4
# use_abs_pos_emb: True
attn_layers:
  _target_: x_transformers.x_transformers.Encoder
  dim: 512
  depth: 8
  heads: 8
  ff_glu: True
  rel_pos_bias: True
  attn_dropout: 0.4
  ff_dropout: 0.4