_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1
max_epochs: 500

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

#resume_from_checkpoint: null
log_every_n_steps: 1